spring:
  datasource:
    url: jdbc:mysql://localhost/reactive-shop?useUnicode=true&characterEncoding=UTF-8&
      autoReconnect=true&useSSL=false&useJDBCCompliantTimezoneShift=true&
      useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
